# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

algorithm: FAIRL
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.00003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
imitation:
  epochs: 5
  learning_rate: 0.00003
  replay_size: 3
  r1_reg_coeff: 0.1
